# Generated by Django 4.1.7 on 2023-03-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="name",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
