# Generated by Django 4.1.7 on 2023-03-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todoitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="is_completed",
            new_name="is_comleted",
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
