# Generated by Django 4.1.7 on 2023-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_rename_is_completed_todoitem_is_comleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="is_comleted",
            new_name="is_completed",
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
